### ISSUE TITLE
Blocking issue : jenkins can't be started - 2.2.40

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8-devops#65]
Jenkins job when started for CanaryReleaseStageAndApprove with camel cdi archetype hangs during build and generates this error "Waiting for next available executor"

```
Started by user anonymous
Fetching changes from the remote Git repository
Checking out Revision 16b0ef67a8de1142a9d247556d52a8e3cde2212f (refs/remotes/origin/master)
Running: Allocate node : Start
Still waiting to schedule task
Waiting for next available executor
```

**Comment by rawlingsj** [comment]
So just took a quick look and I think because we have a trusted build setup with dockerhub, a new fabric8 jenkernetes image was created which disables the executor [see](https://github.com/fabric8io/jenkernetes-docker/commit/8f35ecbd0af28b4760a9ca1dc6928629e6b5ecf4), also because we dont yet use a tagged version (this needs fixing) it means that you've received that change before we've released the new jenkins fabric8 app.  

I've just looked at the new RC in the jenkins app and it's referencing an image that's not in dockerhub yet [fabric8/jenkins-swarm-client](https://github.com/fabric8io/fabric8-devops/blob/master/jenkins/src/main/java/io/fabric8/apps/jenkins/JenkinsModelProcessor.java#L57), @iocanel does a trusted build need to be set up or an image pushed?

**Comment by cmoulliard** [comment]
Hope that this problem will be fixed tomorrow and that a tagged version of jenkins will released also.

@iocanel 
I have tested what you suggested ("edit groovy.file and change node with node('swarm')") without sucess

**Comment by cmoulliard** [comment]
@iocanel Can we revert your commit here ("https://github.com/fabric8io/jenkernetes-docker/commit/8f35ecbd0af28b4760a9ca1dc6928629e6b5ecf4") to be able to have an environment which is still working as I will demo Fabric8 & DevOps

**Comment by rawlingsj** [comment]
@cmoulliard I've verified @iocanel changes and am just testing the create project.  If this works then I'll kick off a release tonight so that the new release works with the jenkins swarm clients.  This means you can scale up the jenkins swarm client to add more executors... very cool!!

`oc scale --replicas=2 replicationcontrollers jenkins-swarm-client`

NOTE I scaled to 3 on my VM and I started to get 504 errors so you may want to delete any unused replication controllers when testing this using the vagrant image.

**Comment by cmoulliard** [comment]
@rawlingsj I see that you have pushed the modification to use node('swarm'). Can we already use this code with docker image published 2 days ago by Ioannis OR do we have to wait till a new release is published (and tagged) ?

**Comment by cmoulliard** [comment]
As code has been reverted, we can close it
